version: '3.6'
services:
  notebook:
    build: .
    image: ocampor/notebook:1.0.0-base
    ports:
      - 8000:8000
    volumes:
      - '${DATA_PATH}:/home/ocampor/data'
      - './notebooks:/home/ocampor/notebooks'

